#!/usr/bin/env python3

# Modified from: https://github.com/faensi/svg_to_png-converter
# Author: faensi, modified by Hantong Chen
# License: MIT
# Usage: python helper.py -i ./logo.big.png -s 16 24 32 36 48 64 96 128 256 320 512 --webp --overwrite
# Notice: logo.big.png is generated by Adobe Illustrator.

import os
import argparse
import cairosvg
import PIL.Image

def generate_icons(input_img, sizes, output_dir, overwrite=False, generate_webp=False):
    PIL.Image.MAX_IMAGE_PIXELS = 1024 * 1024 * 1024
    is_png_input = input_img.lower().endswith('.png')

    for size in sizes:
        output_png = os.path.join(output_dir, f'{size}x{size}.png')
        if not os.path.exists(output_png) or overwrite:
            if is_png_input:
                with PIL.Image.open(input_img) as img:
                    resized_img = img.resize((size, size), PIL.Image.Resampling.LANCZOS)
                    resized_img.save(output_png, 'PNG')
            else:
                cairosvg.svg2png(url=input_img, write_to=output_png, output_width=size, output_height=size)
            print(f'Generated {output_png}')
        else:
            print(f'Skipped {output_png}, already exists.')
        
        if generate_webp:
            output_webp = os.path.join(output_dir, f'{size}x{size}.webp')
            if not os.path.exists(output_webp) or overwrite:
                with PIL.Image.open(output_png) as img:
                    img.save(output_webp, 'WEBP', quality=100)
                print(f'Generated {output_webp}')
            else:
                print(f'Skipped {output_webp}, already exists.')

def main():
    parser = argparse.ArgumentParser(description='Convert SVG or PNG file to PNG and WebP icons of specified sizes.')
    parser.add_argument('-i', '--input', required=True, help='Input SVG file or PNG file path.')
    parser.add_argument('-o', '--output_dir', default='icons', help='Output directory for icon files.')
    parser.add_argument('-s', '--sizes', nargs='+', type=int, default=[16, 32, 64, 128, 256],
                        help='List of icon sizes to generate.')
    parser.add_argument('--overwrite', action='store_true', help='Overwrite existing files.')
    parser.add_argument('--webp', action='store_true', help='Generate WebP format in addition to PNG.')
    
    args = parser.parse_args()
    
    input_img = args.input
    output_dir = args.output_dir
    sizes = args.sizes
    overwrite = args.overwrite
    generate_webp = args.webp
    
    if not os.path.exists(input_img):
        print(f'Error: Input file {input_img} does not exist.')
        return

    if not (input_img.lower().endswith('.svg') or input_img.lower().endswith('.png')):
        print(f'Error: Input file must be an SVG or PNG file.')
        return
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    generate_icons(input_img, sizes, output_dir, overwrite, generate_webp)

if __name__ == "__main__":
    main()